# log-level is the global log level for Dirk logging.
log-level: Debug

server:
  # id should be randomly chosen 8-digit numeric ID; it must be unique across all of your Dirk instances.
  id: 73690039
  # name is the name of your server, as specified in its SSL certificate.
  name: dirk
  # listen-address is the interface and port on which Dirk will listen for requests; change `127.0.0.1`
  # to `0.0.0.0` to listen on all network interfaces.
  listen-address: 0.0.0.0:13141
# storage-path is the path where information created by the slashing protection system is stored.
storage-path: /data/protection
certificates:
  # server-cert is the majordomo URL to the server's certificate.
  server-cert: file:///config/certs/dirk.crt
  # server-key is the majordomo URL to the server's key.
  server-key: file:///config/certs/dirk.key
  # ca-cert is the certificate of the CA that issued the client certificates.  If not present Dirk will use
  # the standard CA certificates supplied with the server.
  ca-cert: file:///config/certs/ca.crt
# stores is a list of locations and types of Ethereum 2 stores.  If no stores are supplied Dirk will use the
# default filesystem store.
stores:
- name: Local
  type: filesystem
  location: /wallets
metrics:
  # listen-address is where Dirk's Prometheus server will present.  If this value is not present then Dirk
  # will not gather metrics.
  listen-address: 0.0.0.0:8081
peers:
  # These are the IDs and addresses of the peers with which Dirk can communicate for distributed key generation.
  # At a minimum it must include this instance.
  73690039: dirk:13141
unlocker:
  # wallet-passphrases is a list of passphrases that can be used to unlock wallets.  Each entry is a majordomo URL.
  wallet-passphrases:
  - file:///config/passphrases/wallet-passphrase.txt
  # account-passphrases is a list of passphrases that can be used to unlock wallets.  Each entry is a majordomo URL.
  account-passphrases:
  - file:///config/passphrases/account-passphrase.txt
process:
  # generation-passphrase is the passphrase used to encrypt newly-generated accounts.  It is a majordomo URL.
  generation-passphrase: file:///config/passphrases/account-passphrase.txt
permissions:
  # This permission allows client1 the ability to carry out all operations on accounts in wallet1.
  vouch:
    .*: All