{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Prysm Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Lighthouse Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_head_state_latest_block_slot"
    }
   ]
  },
  {
   "title": "Teku Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Active Staking Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vouch_accountmanager_accounts_total"
    }
   ]
  },
  {
   "title": "Last Vouch Start",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vouch_start_time_secs*1000" }
   ]
  },
  {
   "title": "Last Dirk Start",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "dirk_start_time_secs*1000" }
   ]
  },
  {
   "title": "Last Prysm Start",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds*1000"
    }
   ]
  },
  {
   "title": "Last Teku Start",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds*1000"
    }
   ]
  },
  {
   "title": "Vouch Processed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vouch_attestation_process_requests_total"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "beacon_peer_count" },
    { "expr": "p2p_peer_count" },
    {
     "expr": "libp2p_peer_connected_peers_total"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester*100"
    },
    {
     "expr": "(total_voted_target_balances/total_eligible_balances)*100"
    },
    {
     "expr": "(beacon_previous_live_validators/beacon_previous_active_validators)*100"
    }
   ]
  },
  {
   "title": "Dirk Processed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dirk_signer_process_requests_total"
    }
   ]
  }
 ]
}