{
 "title": "Agents",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Agents",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libp2p_peers_identity", "legendFormat": "{{agent}}" },
    { "expr": "sum(libp2p_peers_identity)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Agents (now)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "libp2p_peers_identity", "legendFormat": "{{agent}}" }
   ]
  },
  {
   "title": "Agents (4h)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[4h])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (1d)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[1d])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (7d)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[7d])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (30d)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[30d])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (now)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "libp2p_peers_identity", "legendFormat": "{{agent}}" }
   ]
  },
  {
   "title": "Agents (4h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[4h])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (1d)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[1d])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (7d)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[7d])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "Agents (30d)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(libp2p_peers_identity[30d])",
     "legendFormat": "{{agent}}"
    }
   ]
  }
 ]
}