{
 "title": "nimbus",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(process_virtual_memory_bytes,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "resources (${instance})",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval])) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "min without (node) (process_open_fds{instance=\"${instance}\"})",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "min without (node) (process_resident_memory_bytes{instance=\"${instance}\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "min without (node) (nim_gc_mem_bytes{instance=\"${instance}\"})",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "min without (node) (nim_gc_mem_occupied_bytes{instance=\"${instance}\"})",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "open streams (${instance})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (libp2p_open_streams{instance=\"${instance}\"})",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "peers (${instance})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (libp2p_peers{instance=\"${instance}\"})",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "min without (node) (libp2p_pubsub_peers{instance=\"${instance}\"})",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "min without (node) (nbc_peers{instance=\"${instance}\"})",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "GC heap objects (${instance})",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min without (node) (nim_gc_heap_instance_occupied_bytes{instance=\"${instance}\"})",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "validators (${instance})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (beacon_active_validators{instance=\"${instance}\"})",
     "legendFormat": "current validators"
    }
   ]
  },
  {
   "title": "blocks/slot (${instance})",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_blocks_received_total{instance=\"${instance}\"}[$__rate_interval])) * 12",
     "legendFormat": "received"
    },
    {
     "expr": "min without (node) (rate(beacon_blocks_proposed_total{instance=\"${instance}\"}[$__rate_interval])) * 12",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "pool.cachedStates (${instance})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min without (node) (beacon_state_data_cache_hits_total{instance=\"${instance}\"}) * 100 / (min without (node) (beacon_state_data_cache_hits_total{instance=\"${instance}\"}) + min without (node) (beacon_state_data_cache_misses_total{instance=\"${instance}\"}))",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "attestations/slot (${instance})",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_attestations_received_total{instance=\"${instance}\"}[$__rate_interval])) * 12",
     "legendFormat": "received"
    },
    {
     "expr": "min without (node) (rate(beacon_attestations_sent_total{instance=\"${instance}\"}[$__rate_interval])) * 12",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "RSS mem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (process_resident_memory_bytes{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "current slot",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (beacon_slot{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "att'ns sent #all",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(min without (node) (beacon_attestations_sent_total))"
    }
   ]
  },
  {
   "title": "att'ns recv'd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (beacon_attestations_received_total{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "received attestation delay (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_attestation_delay_bucket{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "current epoch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (beacon_current_epoch{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "current justified epoch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (beacon_current_justified_epoch{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "runtime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - min without (node) (process_start_time_seconds{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (nbc_peers{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "last finalized epoch",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min without (node) (beacon_finalized_epoch{instance=\"${instance}\"})"
    }
   ]
  },
  {
   "title": "received aggregate delay (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_aggregate_delay_bucket{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "received beacon block delay (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_block_delay_bucket{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "storeBlock() duration (s) (${instance})",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "min without (node) (rate(beacon_store_block_duration_seconds_bucket{instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "validator rewards / epoch (${instance})",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min without (node) (rate(attached_validator_balance_total{instance=\"${instance}\"}[$__rate_interval]) * 384 / 1000000000)",
     "legendFormat": "GWei"
    }
   ]
  },
  {
   "title": "SQLite3 (${instance})",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min without (node) (sqlite3_memory_used_bytes{instance=\"${instance}\"})",
     "legendFormat": "Memory used"
    }
   ]
  }
 ]
}