version: "3.7"
services:
  stereum-init:
    image: stereum/init:buster
    restart: "no"
    volumes:
      - ./wallets:/mnt/wallets

  validator-import-launchpad:
    image: stereum/lighthouse:${LIGHTHOUSE_DOCKER_TAG}
    user: "2000"
    depends_on:
      - stereum-init
    env_file: ./config/lighthouse/validator.env
    entrypoint: /opt/app/start/import-launchpad-wallet.sh
    volumes:
      - ./wallets:/opt/app/validator
      - ./launchpad:/opt/app/launchpad

#EOF