############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

accept-terms-of-use: yes

datadir: /data

#######################
# Connectivity settings 
p2p-host-ip: "54.187.225.226"
p2p-host-dns: ""

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0

grpc-gateway-host: 0.0.0.0
grpc-gateway-port: 3500

# disable scan of local network
p2p-denylist: ["private"]

# changing this also needs to be changed in docker-compose.yaml!
p2p-tcp-port: 13000

p2p-max-peers: 100

##############################
# Connection to geth container
http-web3provider: http://geth:8545

fallback-web3provider: []

block-batch-limit: 512

mainnet: yes

# EOF
