version: "3.7"
services:
  stereum-init:
    image: stereum/init:buster
    restart: "no"
    volumes:
      - ./data/nimbus:/mnt/validator
      - ./launchpad:/mnt/validator_keys  

  validator-import-launchpad:
    container_name: validator-import-launchpad
    image: stereum/nimbus:${NIMBUS_DOCKER_TAG}
    user: "2000"
    depends_on:
      - stereum-init
    command: deposits import /opt/app/validator_keys --data-dir=/opt/app/validator --network=pyrmont
    volumes:
      - ./data/nimbus/validator:/opt/app/validator
      - ./launchpad:/opt/app/validator_keys
