version: "3.7"
services:
  stereum-init:
    image: stereum/init:buster
    restart: "no"
    volumes:
      - ./launchpad:/mnt/validator_keys
      - ./data/lodestar/validator:/mnt/validator

  validator-import-launchpad:
    container_name: validator-import-launchpad
    image: stereum/lodestar:${LODESTAR_DOCKER_TAG}
    user: "2000"
    depends_on:
      - stereum-init
    command: account validator import --network mainnet --directory /opt/app/validator_keys --keystoresDir /opt/app/keystores --secretsDir /opt/app/secrets
    volumes:
      - ./launchpad:/opt/app/validator_keys
      - ./data/lodestar/validator/keystores:/opt/app/keystores
      - ./data/lodestar/validator/secrets:/opt/app/secrets

  validator-list-accounts:
    container_name: validator-list-accounts
    image: stereum/lodestar:${LODESTAR_DOCKER_TAG}
    user: "2000"
    command: account validator list --network mainnet --keystoresDir /opt/app/keystores --secretsDir /opt/app/secrets
    volumes:
      - ./data/lodestar/validator/keystores:/opt/app/keystores
      - ./data/lodestar/validator/secrets:/opt/app/secrets

# EOF
