version: "3.7"
services:
  stereum-init:
    image: stereum/init:buster
    restart: "no"
    volumes:
      - ./data/lodestar/validator:/mnt/validator

  exit-validator:
    image: stereum/lodestar:${LODESTAR_DOCKER_TAG}
    user: "2000"
    depends_on:
      - stereum-init
    command: account validator voluntary-exit --network prater --force --server http://beacon:9596 --keystoresDir /opt/app/keystores --secretsDir /opt/app/secrets --validatorsDbDir /opt/app/validator-db --publicKey ${PUBKEY}
    volumes:
      - ./data/lodestar/validator/keystores:/opt/app/keystores
      - ./data/lodestar/validator/secrets:/opt/app/secrets
      - ./data/lodestar/validator/validator-db:/opt/app/validator-db

# EOF
