{
 "title": "Lodestar",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "VM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "External Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_external_memory_bytes" }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles" }
   ]
  },
  { "title": "Chain Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "targets": [
    { "expr": "beaconchain_head_slot" }
   ]
  },
  {
   "title": "Current Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "targets": [
    { "expr": "beaconchain_finalized_epoch" }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 18 },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Head Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "beaconchain_head_slot" }
   ]
  }
 ]
}