########################################
##
## Read up on parameters on
## https://chainsafe.github.io/lodestar/
##
########################################

#########
# Network
network: prater

##########
# Database
rootDir: /opt/app/beacon

##############################
# Connection to geth container
eth1.providerUrls: http://geth:8545

#######################
# Beacon rest api
api.rest.enabled: true
api.rest.port: 9596
api.rest.host: "0.0.0.0"

#########
# Metrics
metrics.enabled: true
metrics.serverPort: 8008
metrics.listenAddr: "0.0.0.0"

#EOF
