########################################
##
## Read up on parameters on
## https://chainsafe.github.io/lodestar/
##
########################################
 
#########
# Network
network: prater

##########
# Database
rootDir: /opt/app/beacon

##############
# Connectivity
server: http://beacon:9596

###############################################
# Validator database, accounts & key management
validatorsDbDir: /opt/app/validator-db
keystoresDir: /opt/app/keystores
secretsDir: /opt/app/secrets

##########
# Graffiti
graffiti: stereum.net

#EOF
