{
 "title": "Block Processing",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Block Processing Metrics\n\nMetrics collected from a Lighthouse Beacon Node about a `BeaconChain` processing `BeaconBlocks`.\n\nCollected from the `beacon_chain` crate.\n\n\n\n"
   },
   "content": "\n# Block Processing Metrics\n\nMetrics collected from a Lighthouse Beacon Node about a `BeaconChain` processing `BeaconBlocks`.\n\nCollected from the `beacon_chain` crate.\n\n\n\n"
  },
  {
   "title": "Block Processing Total Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum[5m])\n/\nrate(beacon_block_processing_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Read from database\n\n\nCheck that the hash isn't already known in the database, load the block and state for processing.\n"
   },
   "content": "\n### Read from database\n\n\nCheck that the hash isn't already known in the database, load the block and state for processing.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "options": {
    "content": "\n### Committees/Shuffling\n\n\nCheck that the committees cache is build, building if not.\n"
   },
   "content": "\n### Committees/Shuffling\n\n\nCheck that the committees cache is build, building if not.\n"
  },
  {
   "title": "Block Processing DB Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_db_read_seconds_sum[5m])\n/\nrate(beacon_block_processing_db_read_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing DB Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_db_write_seconds_sum[5m])\n/\nrate(beacon_block_processing_db_write_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Committee Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_committee_building_seconds_sum[5m])\n/\nrate(beacon_block_processing_committee_building_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 14 },
   "options": {
    "content": "\n### Run per_block_processing\n\n\nThe core `state_processing::per_block_processing` verification/state updating function, as defined in the spec.\n"
   },
   "content": "\n### Run per_block_processing\n\n\nThe core `state_processing::per_block_processing` verification/state updating function, as defined in the spec.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "\n### Tree hash the beacon state\n\n\nGet the merkle root of the state after `state_processing::per_block_processing`\n"
   },
   "content": "\n### Tree hash the beacon state\n\n\nGet the merkle root of the state after `state_processing::per_block_processing`\n"
  },
  {
   "title": "Block Processing Core-Processing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_core_seconds_sum[5m])\n/\nrate(beacon_block_processing_core_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing State Hashing Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "options": {
    "content": "\n### Update the fork choice algorithm\n\n\nSubmit the block (and all containied attestation) to the LMD GHOST fork choice algorithm. Does not find the head, just updates the votes.\n"
   },
   "content": "\n### Update the fork choice algorithm\n\n\nSubmit the block (and all containied attestation) to the LMD GHOST fork choice algorithm. Does not find the head, just updates the votes.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "options": {
    "content": "\n### Find the new head\n\n\nRun the LMD GHOST `find_head` algorithm and find the new head `BeaconBlock`."
   },
   "content": "\n### Find the new head\n\n\nRun the LMD GHOST `find_head` algorithm and find the new head `BeaconBlock`."
  },
  {
   "title": "Block Processing Fork Choice Register Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_fork_choice_register_seconds_sum[5m])\n/\nrate(beacon_block_processing_fork_choice_register_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Block Processing Find Head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_fork_choice_find_head_seconds_sum[5m])\n/\nrate(beacon_block_processing_fork_choice_find_head_seconds_count[5m])"
    }
   ]
  }
 ]
}